version: '2'
services:
  traefik-conf:
    metadata:
      traefik: &id001
        ssl_crt: ''
        ssl_key: ''
    retain_ip: true
    scale: 1
    start_on_create: true
  traefik:
    metadata:
      traefik: *id001
    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  aws-elb-registrator:
    metadata:
      traefik: *id001
    retain_ip: true
    scale: 1
    start_on_create: true
