.catalog:
  name: "rancher-reaper"
  version: "v0.0.1"
  description: "rancher reaper"
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: "AWS_ACCESS_KEY_ID"
      label: "aws access key id"
      description: "required key to connect to aws account"
      type: "string"
      required: true
    - variable: "AWS_SECRET_ACCESS_KEY"
      label: "aws secret access key"
      description: "required key to connect to aws account"
      type: "string"
      required: true

rancher-reaper:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
