.catalog:
  name: "traefik"
  version: "v1.0.0"
  description: "traefik proxy"
  minimum_rancher_version: v1.2.0-pre4-rc1


traefik-conf:
  metadata:
    traefik:
      ssl_crt: ''
      ssl_key: ''
  retain_ip: true
  scale: 1
  start_on_create: true
traefik:
  metadata:
    traefik:
  retain_ip: true
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 80
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000
