.catalog:
  name: "traefik"
  version: "v0.0.1"
  description: "traefik proxy"
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: "TRAEFIK_DOMAIN"
      label: "traefik base domain"
      description: "domain name that will be used to forward traefik through external elb to rancher agent nodes, example : "
      type: "string"
      required: true


traefik-conf:
  metadata:
    traefik:
      ssl_crt: ''
      ssl_key: ''
  retain_ip: true
  scale: 1
  start_on_create: true
proxy:
  metadata:
    proxy:
  retain_ip: true
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 80
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000
